[build]
  # Build command (not needed for static site)
  command = "echo 'Static site - no build needed'"
  
  # Publish directory
  publish = "."

[build.environment]
  # Node.js version (if needed for build tools)
  NODE_VERSION = "18"

# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
